### ISSUE TITLE
Keyboard symbols/ALT codes instead of emojis?

### ISSUE THREAD

**Issue by cathyjhu** [phibr0/obsidian-emoji-shortcodes#41]
I realized that for a few emojis, the usual emoji is replaced by the keyboard symbol (Windows ALT codes?). I included screenshots below, and the original emojis I was looking for are ❤️ and ☔️:

![Screen Shot 2022-11-12 at 9 30 52 PM](https://user-images.githubusercontent.com/95381336/201502873-4451cca7-9ee2-4329-9f3b-a61c2f8edb32.png)
![Screen Shot 2022-11-12 at 9 31 00 PM](https://user-images.githubusercontent.com/95381336/201502874-65247250-49ae-4c48-a33f-ca6c2a132d4e.png)

**Comment by taneltm** [comment]
Looks like the font that's loaded by Obsidian doesn't include some of the emojis.
I made a CSS snippet to fix those kinds of issues for me:

```css
@font-face {
  font-family: 'Noto Color Emoji';
  src: url(https://rawcdn.githack.com/googlefonts/noto-emoji/9a5261d871451f9b5183c93483cbd68ed916b1e9/fonts/NotoColorEmoji.ttf);
}

:root {
  --default-font: -apple-system, BlinkMacSystemFont, Segoe UI,
      Helvetica, Arial, sans-serif, Apple Color Emoji,
      Noto Color Emoji;
  --editor-font: 'Hack Nerd Font', 'Source Code Pro',
      ui-monospace, SFMono-Regular, SF Mono, Menlo,
      Consolas, Liberation Mono, monospace;
}
```

Without that snippet, I do have the heart and umbrella emojis, but the heart is gray instead of red and some of the newer emojis like `:anatomical_heart:` are just squares.

I made that snippet over a year ago, so I don't know if there are any side-effects.

The plugin itself is fine.
